-- 添加存储大小字段
ALTER TABLE image_history ADD COLUMN IF NOT EXISTS file_size INTEGER DEFAULT 0;
ALTER TABLE video_history ADD COLUMN IF NOT EXISTS file_size INTEGER DEFAULT 0;
ALTER TABLE character_library ADD COLUMN IF NOT EXISTS file_size INTEGER DEFAULT 0;
